"""Intitial migration

Revision ID: 1457244a0fb3
Revises: 8edf3ce91214
Create Date: 2024-06-16 12:04:32.478989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1457244a0fb3'
down_revision = '8edf3ce91214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sat', schema=None) as batch_op:
        batch_op.drop_column('new')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
