"""new row

Revision ID: 8edf3ce91214
Revises: 21430959be48
Create Date: 2024-06-16 12:01:19.747495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8edf3ce91214'
down_revision = '21430959be48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sat', schema=None) as batch_op:
        batch_op.drop_column('new')

    # ### end Alembic commands ###
